// Generated by gencpp from file string_service_demo/StringService.msg
// DO NOT EDIT!


#ifndef STRING_SERVICE_DEMO_MESSAGE_STRINGSERVICE_H
#define STRING_SERVICE_DEMO_MESSAGE_STRINGSERVICE_H

#include <ros/service_traits.h>


#include <string_service_demo/StringServiceRequest.h>
#include <string_service_demo/StringServiceResponse.h>


namespace string_service_demo
{

struct StringService
{

typedef StringServiceRequest Request;
typedef StringServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringService
} // namespace string_service_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::string_service_demo::StringService > {
  static const char* value()
  {
    return "7229f1b0de733d7956dd646adcbf7e06";
  }

  static const char* value(const ::string_service_demo::StringService&) { return value(); }
};

template<>
struct DataType< ::string_service_demo::StringService > {
  static const char* value()
  {
    return "string_service_demo/StringService";
  }

  static const char* value(const ::string_service_demo::StringService&) { return value(); }
};


// service_traits::MD5Sum< ::string_service_demo::StringServiceRequest> should match
// service_traits::MD5Sum< ::string_service_demo::StringService >
template<>
struct MD5Sum< ::string_service_demo::StringServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::string_service_demo::StringService >::value();
  }
  static const char* value(const ::string_service_demo::StringServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::string_service_demo::StringServiceRequest> should match
// service_traits::DataType< ::string_service_demo::StringService >
template<>
struct DataType< ::string_service_demo::StringServiceRequest>
{
  static const char* value()
  {
    return DataType< ::string_service_demo::StringService >::value();
  }
  static const char* value(const ::string_service_demo::StringServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::string_service_demo::StringServiceResponse> should match
// service_traits::MD5Sum< ::string_service_demo::StringService >
template<>
struct MD5Sum< ::string_service_demo::StringServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::string_service_demo::StringService >::value();
  }
  static const char* value(const ::string_service_demo::StringServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::string_service_demo::StringServiceResponse> should match
// service_traits::DataType< ::string_service_demo::StringService >
template<>
struct DataType< ::string_service_demo::StringServiceResponse>
{
  static const char* value()
  {
    return DataType< ::string_service_demo::StringService >::value();
  }
  static const char* value(const ::string_service_demo::StringServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STRING_SERVICE_DEMO_MESSAGE_STRINGSERVICE_H
