// Generated by gencpp from file string_service_demo/StringServiceResponse.msg
// DO NOT EDIT!


#ifndef STRING_SERVICE_DEMO_MESSAGE_STRINGSERVICERESPONSE_H
#define STRING_SERVICE_DEMO_MESSAGE_STRINGSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace string_service_demo
{
template <class ContainerAllocator>
struct StringServiceResponse_
{
  typedef StringServiceResponse_<ContainerAllocator> Type;

  StringServiceResponse_()
    : result()  {
    }
  StringServiceResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::string_service_demo::StringServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::string_service_demo::StringServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StringServiceResponse_

typedef ::string_service_demo::StringServiceResponse_<std::allocator<void> > StringServiceResponse;

typedef boost::shared_ptr< ::string_service_demo::StringServiceResponse > StringServiceResponsePtr;
typedef boost::shared_ptr< ::string_service_demo::StringServiceResponse const> StringServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::string_service_demo::StringServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::string_service_demo::StringServiceResponse_<ContainerAllocator1> & lhs, const ::string_service_demo::StringServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::string_service_demo::StringServiceResponse_<ContainerAllocator1> & lhs, const ::string_service_demo::StringServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace string_service_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::string_service_demo::StringServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::string_service_demo::StringServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::string_service_demo::StringServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::string_service_demo::StringServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string_service_demo/StringServiceResponse";
  }

  static const char* value(const ::string_service_demo::StringServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
;
  }

  static const char* value(const ::string_service_demo::StringServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::string_service_demo::StringServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::string_service_demo::StringServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STRING_SERVICE_DEMO_MESSAGE_STRINGSERVICERESPONSE_H
